### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by ironiridis** [everyonesdesign/disable-google-search-text-highlights#4]
Per #1 it would be great to have the option to donate to the maintainer/author.

**Comment by everyonesdesign** [comment]
Hello! 

Thank you! 

Added a link to Readme (also to Chrome Web Store description, it'll appear there when the version 1.0.0 is approved by the mods): [https://buymeacoff.ee/everyonesdesign](https://buymeacoff.ee/everyonesdesign)
