### ISSUE TITLE
How to build and install locally

### ISSUE THREAD

**Issue by vemv** [everyonesdesign/disable-google-search-text-highlights#9]
Hi,

great extension, thank you for your work.

I'd like to install it in a secure environment.

Would you generously add a brief section on local building/installing?

Coffee will be indeed bought as you suggest ☕️☕️

Cheers - V

**Comment by everyonesdesign** [comment]
Hello!

Added [this section](https://github.com/everyonesdesign/disable-google-search-text-highlights#how-to-install-it-from-source) to the documentation explaining the manual installation. This is for Google Chrome, for other browsers different process might be required (or it might not be possible).

Let me know if you have any further questions regarding this.

Have a nice day!
